// css.ts — generates CSS custom properties from token themes
import type { Theme } from './tokens.js';

function toKebab(s: string): string {
  return s.replace(/([A-Z])/g, (c) => `-${c.toLowerCase()}`);
}

function flattenColors(color: Theme['color'], prefix: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [group, values] of Object.entries(color)) {
    for (const [key, value] of Object.entries(values as Record<string, string>)) {
      result[`${prefix}-color-${toKebab(group)}-${toKebab(key)}`] = value;
    }
  }
  return result;
}

function flattenTheme(theme: Theme): Record<string, string> {
  const vars: Record<string, string> = {};
  const prefix = '--pb';

  // colors
  Object.assign(vars, flattenColors(theme.color, prefix));

  // space
  for (const [key, value] of Object.entries(theme.space)) {
    vars[`${prefix}-space-${key}`] = `${value}px`;
  }

  // radius
  for (const [key, value] of Object.entries(theme.radius)) {
    vars[`${prefix}-radius-${key}`] = `${value}px`;
  }

  // font family
  vars[`${prefix}-font-family-sans`] = theme.fontFamily.sans;

  // font size
  for (const [key, value] of Object.entries(theme.fontSize)) {
    vars[`${prefix}-font-size-${key}`] = `${value}px`;
  }

  // font weight
  for (const [key, value] of Object.entries(theme.fontWeight)) {
    vars[`${prefix}-font-weight-${toKebab(key)}`] = String(value);
  }

  // line height
  for (const [key, value] of Object.entries(theme.lineHeight)) {
    vars[`${prefix}-line-height-${key}`] = String(value);
  }

  return vars;
}

function renderBlock(selector: string, vars: Record<string, string>): string {
  const sorted = Object.entries(vars).sort(([a], [b]) => a.localeCompare(b));
  const lines = sorted.map(([k, v]) => `  ${k}: ${v};`).join('\n');
  return `${selector} {\n${lines}\n}`;
}

export function themesToCss(dark: Theme, light: Theme): string {
  const darkVars = flattenTheme(dark);
  const lightVars = flattenTheme(light);

  // Only emit changed values in the light override block
  const lightOverrides: Record<string, string> = {};
  for (const [key, value] of Object.entries(lightVars)) {
    if (darkVars[key] !== value) {
      lightOverrides[key] = value;
    }
  }

  const lines: string[] = [
    '/* AUTOGENERATED — DO NOT EDIT — source: packages/design-tokens/src/tokens.ts */',
    '',
    renderBlock(':root, [data-theme="dark"]', darkVars),
    '',
    renderBlock('[data-theme="light"]', lightOverrides),
  ];

  return lines.join('\n') + '\n';
}

// When run directly as a script, emit CSS to stdout
import { fileURLToPath } from 'node:url';
import { darkTheme, lightTheme } from './tokens.js';

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  process.stdout.write(themesToCss(darkTheme, lightTheme));
}
