/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: operations['AuthController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login with email and password */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/magic-link/request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a magic-link login email */
    post: operations['AuthController_requestMagicLinkEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/magic-link/consume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Consume a magic-link token and get tokens */
    post: operations['AuthController_consumeMagicLinkEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/oauth/google/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Start Google OAuth flow (redirects to Google) */
    get: operations['AuthController_googleStart'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/oauth/google/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Google OAuth callback */
    get: operations['AuthController_googleCallback'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/totp/enable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enable TOTP 2FA for the current user */
    post: operations['AuthController_totpEnable'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/totp/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify and activate TOTP for the current user */
    post: operations['AuthController_totpVerify'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate refresh token and get a new access token */
    post: operations['AuthController_refreshTokenEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout and revoke refresh token */
    post: operations['AuthController_logoutEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the current authenticated user */
    get: operations['UsersController_getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me/locale': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the current user locale preference */
    patch: operations['UsersController_updateLocalePreference'];
    trace?: never;
  };
  '/households': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new household */
    post: operations['HouseholdsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/households/invite': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invite a user to the current household */
    post: operations['HouseholdsController_invite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/households/invite/{token}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept a household invitation */
    post: operations['HouseholdsController_acceptInviteEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List transactions for the current household */
    get: operations['TransactionsController_list'];
    put?: never;
    /** Add a manual transaction */
    post: operations['TransactionsController_addManual'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/transactions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single transaction by ID */
    get: operations['TransactionsController_getOne'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch notes or ignored flag on a transaction */
    patch: operations['TransactionsController_patch'];
    trace?: never;
  };
  '/transactions/{id}/mapping': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Set or clear the planned-item mapping for a transaction */
    patch: operations['TransactionsController_setMapping'];
    trace?: never;
  };
  '/transactions/{id}/transfer': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark a transaction as a transfer between own accounts */
    post: operations['TransactionsController_markTransfer'];
    /** Unmark a transaction as a transfer */
    delete: operations['TransactionsController_unmarkTransferHandler'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/transactions/bulk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bulk-map or bulk-act on a set of transactions */
    post: operations['TransactionsController_bulkMap'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/audit-log': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List audit log events for the current household */
    get: operations['AuditController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bank-connections/catalogue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available banks for a given country */
    get: operations['BankController_catalogue'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bank-connections': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List bank connections for the current user */
    get: operations['BankController_listBankConnections'];
    put?: never;
    /** Initiate a new bank connection (starts OAuth consent) */
    post: operations['BankController_initiateBankConnection'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bank-connections/{id}/complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Complete bank OAuth consent callback */
    get: operations['BankController_completeBankConsent'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bank-connections/{id}/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trigger a manual sync for a bank connection */
    post: operations['BankController_refreshConnection'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bank-connections/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Disconnect (delete) a bank connection */
    delete: operations['BankController_disconnectBank'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bank-connections/{id}/reconnect': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Re-initiate consent for an expired bank connection */
    post: operations['BankController_reconnectBank'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bank-connections/{id}/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List bank accounts for a connection */
    get: operations['BankController_listAccounts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{id}/dashboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get plan actuals dashboard */
    get: operations['PlansController_dashboard'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    RegisterDto: {
      /** @example user@example.com */
      email: string;
      /** @example Str0ngPass! */
      password: string;
      /**
       * @default en
       * @enum {string}
       */
      locale: 'en' | 'uk' | 'ru' | 'pl';
    };
    LoginDto: {
      /** @example user@example.com */
      email: string;
      /** @example Str0ngPass! */
      password: string;
      /**
       * @description TOTP code if 2FA is enabled
       * @example 123456
       */
      totp?: string;
    };
    RequestMagicLinkDto: {
      /** @example user@example.com */
      email: string;
    };
    ConsumeMagicLinkDto: {
      /** @description Magic-link token from email */
      token: string;
    };
    VerifyTotpDto: {
      /**
       * @description 6-digit TOTP code
       * @example 123456
       */
      code: string;
    };
    RefreshTokenDto: {
      /** @description Opaque refresh token */
      refreshToken: string;
    };
    LogoutDto: {
      /** @description Refresh token to revoke */
      refreshToken: string;
    };
    UpdateLocaleDto: {
      /**
       * @example en
       * @enum {string}
       */
      locale: 'en' | 'uk' | 'ru' | 'pl';
    };
    CreateHouseholdDto: {
      /** @example Smith Family */
      name: string;
      /**
       * @description ISO 4217 currency code
       * @example PLN
       */
      baseCurrency?: string;
    };
    InviteToHouseholdDto: {
      /** @example member@example.com */
      email: string;
    };
    AddManualTransactionDto: {
      /** @description Bank account ID */
      accountId: string;
      /**
       * @description Date of transaction (ISO 8601)
       * @example 2024-06-15
       */
      occurredOn: string;
      /**
       * @description Amount in minor currency units (e.g. cents)
       * @example 1500
       */
      amountMinor: number;
      /**
       * @description ISO 4217 currency code
       * @example PLN
       */
      currency: string;
      /** @example Coffee at Starbucks */
      description: string;
      /** @example Starbucks */
      merchant?: string | null;
      /** @example Team lunch */
      notes?: string | null;
    };
    PatchTransactionDto: {
      /** @example Corrected description */
      notes?: string | null;
      /** @description Soft-ignore the transaction from totals */
      ignored?: boolean;
    };
    SetMappingDto: {
      /** @description Planned item ID to map to, or null to unmap */
      plannedItemId: string | null;
    };
    MarkTransferDto: {
      /** @description ID of the counterpart transaction for this transfer */
      counterpartTransactionId?: string | null;
    };
    BulkMapDto: {
      /** @description Transaction IDs to act on */
      ids: string[];
      /** @enum {string} */
      op: 'map' | 'transfer' | 'ignore';
      /** @description Operation-specific payload */
      payload?: Record<string, never>;
    };
    InitiateBankConnectionDto: {
      /** @enum {string} */
      provider: 'gocardless' | 'wise_personal';
      /**
       * @description Provider-specific institution/bank ID
       * @example PKO_BPKOPLPW
       */
      bankId: string;
      /**
       * @description OAuth redirect URI after consent
       * @example https://app.power-budget.test/connect/callback
       */
      redirectUri: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDto'];
      };
    };
    responses: {
      /** @description User registered successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Email already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      /** @description Tokens issued */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_requestMagicLinkEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestMagicLinkDto'];
      };
    };
    responses: {
      /** @description Magic link sent (if account exists) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_consumeMagicLinkEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsumeMagicLinkDto'];
      };
    };
    responses: {
      /** @description Tokens issued */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Token invalid or expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_googleStart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to Google OAuth */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_googleCallback: {
    parameters: {
      query: {
        /** @description OAuth state parameter */
        state: unknown;
        /** @description Authorization code from Google */
        code: unknown;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tokens issued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_totpEnable: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description TOTP secret and QR code URI */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_totpVerify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyTotpDto'];
      };
    };
    responses: {
      /** @description TOTP verified */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized or invalid code */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refreshTokenEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      /** @description New tokens issued */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Refresh token invalid or expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logoutEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LogoutDto'];
      };
    };
    responses: {
      /** @description Logged out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_updateLocalePreference: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateLocaleDto'];
      };
    };
    responses: {
      /** @description Locale updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HouseholdsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateHouseholdDto'];
      };
    };
    responses: {
      /** @description Household created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HouseholdsController_invite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InviteToHouseholdDto'];
      };
    };
    responses: {
      /** @description Invitation sent */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HouseholdsController_acceptInviteEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Invitation token from email */
        token: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Invitation accepted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TransactionsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of transactions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TransactionsController_addManual: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddManualTransactionDto'];
      };
    };
    responses: {
      /** @description Transaction created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TransactionsController_getOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transaction ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Transaction detail */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transaction not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TransactionsController_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transaction ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PatchTransactionDto'];
      };
    };
    responses: {
      /** @description Transaction updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transaction not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TransactionsController_setMapping: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transaction ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetMappingDto'];
      };
    };
    responses: {
      /** @description Mapping updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transaction not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TransactionsController_markTransfer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transaction ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MarkTransferDto'];
      };
    };
    responses: {
      /** @description Marked as transfer */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transaction not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TransactionsController_unmarkTransferHandler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transaction ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Transfer flag removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transaction not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TransactionsController_bulkMap: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkMapDto'];
      };
    };
    responses: {
      /** @description Bulk operation applied */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuditController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of audit events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_catalogue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of bank institutions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_listBankConnections: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of bank connections */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_initiateBankConnection: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InitiateBankConnectionDto'];
      };
    };
    responses: {
      /** @description Consent link returned */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Connection to this bank already exists */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_completeBankConsent: {
    parameters: {
      query: {
        /** @description OAuth state / consent reference */
        state: unknown;
        /** @description OAuth authorization code */
        code: unknown;
      };
      header?: never;
      path: {
        /** @description Bank connection ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Connection activated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Consent not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_refreshConnection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Bank connection ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Refresh enqueued */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Connection not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_disconnectBank: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Bank connection ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Connection removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Connection not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_reconnectBank: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Bank connection ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description New consent link returned */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden or invalid state */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Connection not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BankController_listAccounts: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Bank connection ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of bank accounts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PlansController_dashboard: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Plan ID */
        id: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Plan actuals view */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No household */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Plan not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
